services:
  - type: web
    name: syncpoint-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: '*'
