export const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',
  PING_CHECK: 'ping:check',
  PONG_REPLY: 'pong:reply',

  ROOM_JOIN: 'room:join',
  ROOM_JOINED: 'room:joined',
  ROOM_USER_JOINED: 'room:user_joined',
  ROOM_USER_LEFT: 'room:user_left',
  ROOM_HOST_CHANGED: 'room:host_changed',
  ROOM_LEAVE: 'room:leave',

  CURSOR_UPDATE: 'cursor:update',
  CURSOR_SYNC: 'cursor:sync',
  CURSOR_CLICK: 'cursor:click',
  CURSOR_CLICKED: 'cursor:clicked',
  CURSOR_PING: 'cursor:ping',
  CURSOR_PINGED: 'cursor:pinged',
  CURSOR_CHAT: 'cursor:chat',
  CURSOR_CHATTED: 'cursor:chatted',
  LASER_DRAW: 'laser:draw',
  LASER_DRAWN: 'laser:drawn',

  STATE_COUNTER_UPDATE: 'state:counter:update',
  STATE_COUNTER_CHANGED: 'state:counter:changed',
  STATE_EDITOR_UPDATE: 'state:editor:update',
  STATE_EDITOR_CHANGED: 'state:editor:changed',
  STATE_NOTE_CREATE: 'state:note:create',
  STATE_NOTE_CREATED: 'state:note:created',
  STATE_NOTE_UPDATE: 'state:note:update',
  STATE_NOTE_UPDATED: 'state:note:updated',
  STATE_NOTE_DELETE: 'state:note:delete',
  STATE_NOTE_DELETED: 'state:note:deleted',
  STATE_TOGGLE_UPDATE: 'state:toggle:update',
  STATE_TOGGLE_CHANGED: 'state:toggle:changed',

  REACTION_SEND: 'reaction:send',
  REACTION_BROADCAST: 'reaction:broadcast',
} as const;
